mod SAND is

protecting LOOP-MODE .

sorts Formula .
subsort Nat < Formula .

op _||_  : Formula Formula -> Formula [ctor assoc comm] .
op _._ : Formula Formula -> Formula [ctor assoc comm] .
op _;_  : Formula Formula -> Formula [ctor assoc] .
op EQ(_,_) : Formula Formula -> Bool .

var P Q R S : Formula .

eq P . (Q || R)  = (P . Q) || (P . R) .
eq P ; (Q || R)  = (P ; Q)  || (P ; R) .
eq (Q || R) ; P  = (Q ; P)  || (R ; P) .

ceq EQ(P,Q) = true
  if P = Q .
eq EQ(P,Q) = false .

endm
