mod SAND is

protecting LOOP-MODE .

sorts Formula .
subsort Nat < Formula .

op _||_  : Formula Formula -> Formula [assoc comm] .
op _._ : Formula Formula -> Formula [assoc comm prec 50] .
op _;_  : Formula Formula -> Formula [assoc prec 51] .

var P Q R S : Formula .

rl [dist-.-||] : P . (Q || R) => (P . Q) || (P . R) .
rl [dist-;-||]  : P ; (Q || R)  => (P ; Q)  || (P ; R) .
rl [dist-||-;]  : (Q || R) ; P  => (Q ; P)  || (R ; P) .

endm


